- modules/actors/actor-ffg.js
moved localization for characteristics to a generic function to be called from character and minion data setup.
fixes #19
> Fix for #19

- lang/en.json
- templates/items/ffg-armour-sheet.html
- templates/items/ffg-gear-sheet.html
- templates/items/ffg-shipattachment-sheet.html
- templates/items/ffg-shipweapon-sheet.html
- templates/items/ffg-talent-sheet.html
- templates/items/ffg-weapon-sheet.html
> Added localization for item tabs.

- scss/components/_vehiclesheet.scss
- styles/starwarsffg.css
> Fixed positioning issue with tool tips on vehicle sheet

- modules/actors/actor-sheet-ffg.js
- scss/components/_characteristics.scss
- styles/starwarsffg.css
- templates/actors/ffg-character-sheet.html
- templates/actors/ffg-minion-sheet.html
> remove fieldset to fix console error on save.

- README.md
- modules/actors/actor-sheet-ffg.js
- templates/actors/ffg-character-sheet.html
removed console.log in actor sheet.
> re-added force pool under talents tab.

- README.md
- modules/items/item-sheet-ffg.js
- modules/popout-editor.js
- scss/components/_editor.scss
- scss/components/_forcepowers.scss
- styles/starwarsffg.css
- templates/items/ffg-forcepower-sheet.html
Updated popout editor to allow for custom sizing.
fixes #67
> Added popout editor to force powers sheet.

- README.md
- modules/swffg-main.js
- scss/global/_window.scss
- styles/starwarsffg.css
Not sure this is the best way to do this, but it works as expected.
> Add Dice Symbol rendering to Journal Entries

- README.md
- scss/components/_talents.scss
- styles/starwarsffg.css
> Update style to add scrolls to talent boxes.

- README.md
- modules/actors/actor-sheet-ffg.js
Updated validation for onchange event for skill ranks and characteristics.
fixes #87
> Bug fix for min/max value for skills and characteristics

- README.md
- modules/actors/actor-sheet-ffg.js
- scss/components/_skills.scss
- styles/starwarsffg.css
- templates/actors/dialogs/ffg-skill-characteristic-selector.html
- templates/actors/ffg-character-sheet.html
Not styled yet, but functional,
fixes #72
> Added ability to change characteristic of skill through dialog selector.

- modules/items/item-ffg.js
- modules/items/item-sheet-ffg.js
- templates/items/ffg-specialization-sheet.html
This is a possible fix for moving the Specialization Talent code to the PrepareData section.
> PLEASE REVIEW

- README.md
- modules/actors/actor-ffg.js
- modules/actors/actor-sheet-ffg.js
- modules/items/item-ffg.js
- templates/actors/ffg-character-sheet.html
Fixed ranking display, only ranked talents will now stack, all others will display separately.
fixes #97
> Fixed onclick talent display for specialization talents.

- README.md
- modules/swffg-main.js
- scss/components/_talents.scss
- styles/starwarsffg.css
- templates/items/ffg-specialization-sheet.html
> Added static cost for talents in specialization tree based on row.

- README.md
- modules/swffg-main.js
- scss/components/_talents.scss
- styles/starwarsffg.css
- templates/items/ffg-specialization-sheet.html
> Added css colors for active and passive talents in specialization sheet.

- lang/fr.json
Missing SkillCharacteristicDialogTitle
> Added french localization for new feature

- README.md
- modules/actors/actor-sheet-ffg.js
> fix the localization issue with the change characteristic dialog

- lang/en.json
- modules/importer/data-importer.js
- scss/components/_dataimporter.scss
- styles/starwarsffg.css
- templates/importer/data-importer.html
Added progress bar to import dialog.
> Added localization for data importer.

- README.md
- lib/jxon/jxon.min.js
- modules/importer/data-importer.js
- scss/components/_dataimporter.scss
- styles/starwarsffg.css
- system.json
- templates/importer/data-importer.html
Added OggDude Force Power Import
> Force powers import

- modules/importer/data-importer.js
> Carelessly forgot to remove debugging code.

- README.md
- modules/importer/data-importer.js
- modules/popout-editor.js
- scss/components/_editor.scss
- styles/starwarsffg.css
Now processes REMSETBACK, RESTRICTED, ADDDIFFICULTY, IPDIFFICULTY, and CANTHREAT dice symbols.
Now processes [B][b], [I][i], [H1][h1], [H2][h2], [H3][h3], [H4][h4]. [P], and [BR]
> Additional oggdude editor symbols

- README.md
Added a step by step for special dice roller, so that people see that is is a required action.
> Updated Readme to clarify requirements

- README.md
- modules/actors/actor-sheet-ffg.js
- modules/actors/adversary-sheet-ffg.js
- modules/items/item-ffg.js
- modules/items/item-sheet-ffg.js
- scss/components/_talents.scss
- styles/starwarsffg.css
fixes #138 
Bug fix for new specialization error.
> Bug fix for CSS styling

- README.md
- modules/importer/data-importer.js
example (Heal/Harm only has 4 total rows
> Update force power import, removed unused rows if power does not need them

- README.md
- modules/importer/data-importer.js
- templates/importer/data-importer.html
Also includes Gear Updates.  Will update gear data on subsequent imports of the same data,
> Import gear

- README.md
- modules/importer/data-importer.js
Added compendium item updates to talents and force powers, so that the import will update the data correctly on subsequent imports.
> Added compendium item updates to talents and force powers.

- lang/fr.json
Added latest changes to French version
> Added latest localisation

- README.md
- modules/importer/data-importer.js
fixes #149 
Added error handling, and async file importing.
> Data Imported error handling and async importing

- README.md
- lang/en.json
- modules/actors/actor-ffg.js
- modules/actors/actor-sheet-ffg.js
- modules/swffg-main.js
- templates/actors/ffg-adversary-sheet.html
- templates/actors/ffg-character-sheet.html
(workaround to handle Talents that add soak)
> Added game setting to disable Soak Auto Calculation 

- README.md
- templates/actors/ffg-vehicle-sheet.html
> If issue with pattern matching on text input field for silhouette.

- README.md
- lang/en.json
- modules/importer/data-importer.js
- modules/items/item-ffg.js
- modules/swffg-config.js
- templates/items/ffg-weapon-sheet.html
Added damage add to weapon modifiers.
Added damage calculation for melee/brawl weapons once attached to an actor.
fixes #154
> Added damage from melee/brawl weapons to damage characteristic of weapon

- modules/actors/actor-ffg.js
Integrated a basic armour-only implementation of the defence calculations.
Also refactored _calculateSoak to _calculateDerivedValues to better reflect it's current usage.
> Added basic defence calculation

- README.md
- modules/importer/data-importer.js
use checkbox to enable on importer
> Added import logging

- README.md
- modules/actors/actor-sheet-ffg.js
- modules/actors/adversary-sheet-ffg.js
- modules/helpers/dice-helpers.js
- modules/swffg-main.js
- scss/components/_dicepool.scss
- scss/starwarsffg.scss
- styles/starwarsffg.css
- templates/roll-options.html
Added ad-hoc die rolling by clicking on "die" icon over chat box.
Moved dice-rolling styles out of template into scss.
> Refactor dice code into helper moduler

- README.md
- modules/swffg-config.js
> Fixed incorrect label value in config.

- README-fr.md
- README.md
- modules/swffg-config.js
Typo in label name for Survival
Updated README-fr.md
> Bugfix for #174 & Localisation

- README.md
- templates/actors/ffg-character-sheet.html
Added equipped function for weapons.  It is purely cosmetic.
fixes #119
> Added equipped function for weapons.  It is purely cosmetic.

- README.md
- modules/actors/actor-ffg-options.js
* Config patch, to enable default options
> Patch, to enable default options on charactersheet configuration (#2)

- README.md
- modules/helpers/dice-helpers.js
- modules/importer/data-importer.js
- modules/importer/import-helpers.js
- modules/items/item-ffg.js
- system.json
Fixes Special-Dice-Roller update bug.
> v0.41 hotfix

- README.md
- lang/en.json
- modules/actors/actor-ffg.js
- modules/actors/actor-sheet-ffg.js
- scss/components/_skills.scss
- styles/starwarsffg.css
- templates/actors/dialogs/ffg-skill-new.html
- templates/actors/ffg-character-sheet.html
Added right click context menu to add skills (done from skill header row), and delete a skill by left clicking and selecting `Remove Skill`
Clicking on header for a sections (General, Combat, Knowledge) will add the skill to that grouping.
> Ability to add/remove skills.

- README.md
- modules/items/item-sheet-ffg.js
- scss/components/_species.scss
- scss/starwarsffg.scss
- styles/starwarsffg.css
- template.json
- templates/items/ffg-species-sheet.html
Species values are stored in attributes object.  They will be applied to actors through modifier update.
> Added species item type, values stored in modifiers.

- README.md
- modules/actors/actor-ffg.js
- modules/actors/actor-sheet-ffg.js
- scss/components/_header.scss
- styles/starwarsffg.css
- template.json
- templates/actors/ffg-adversary-sheet.html
- templates/actors/ffg-character-sheet.html
Added characteristic modifiers to character/adversary/minion sheets, now all items with characteristic modifiers will update the value on the sheet.  (TODO: Add some sort of display to see where all the values are coming from)
Added drag/drop of species onto character/adversaries (not minion), any characteristic modifiers will be applied.  (TODO: Stats, Talents, Skills)
> Characteristic Modifiers

- README.md
- scss/components/_minionsheet.scss
- styles/starwarsffg.css
- templates/actors/ffg-minion-sheet.html
Added the skill context menu to minions.
fixes #218
> Fixed the Minion Sheet's scrolling issue

- README.md
- modules/actors/adversary-sheet-ffg.js
Cherry pick commit from v5 branch.
fixes #222
> Fixed issue where soak options were not being used on Adversary Sheet.

- README.md
- templates/actors/ffg-minion-sheet.html
> Fixed issue with minion groupskill calculations

- README.md
- scss/components/_itemcriticalinjurysheet.scss
- styles/starwarsffg.css
- templates/items/ffg-criticaldamage-sheet.html
- templates/items/ffg-criticalinjury-sheet.html
same fix for 227 just for dev branch.
> Fix 227 fordev

- README.md
- lang/en.json
- modules/actors/actor-ffg.js
- modules/actors/actor-sheet-ffg.js
- modules/actors/adversary-sheet-ffg.js
- modules/helpers/modifiers.js
- modules/importer/data-importer.js
- modules/importer/import-helpers.js
- modules/items/item-ffg.js
- modules/items/item-sheet-ffg.js
- modules/swffg-config.js
- templates/actors/ffg-vehicle-sheet.html
- templates/items/ffg-specialization-sheet.html
- templates/parts/shared/ffg-modifiers.html
refactored modifier part 2, fixed issue with weapon mods, added new mod (setback and career skill), updated importer to correctly populate talent and specialization characteristic and stat modifiers.
> Modifer refactor 2

- README.md
- modules/actors/actor-sheet-ffg.js
> Bug Fix #255 - Clicking on critical injuries was not bringing up sheet

- README.md
- modules/actors/actor-sheet-ffg.js
- modules/actors/adversary-sheet-ffg.js
- modules/helpers/partial-templates.js
- modules/items/item-sheet-ffg.js
- scss/components/_itemcriticalinjurysheet.scss
- styles/starwarsffg.css
- templates/actors/ffg-adversary-sheet.html
- templates/actors/ffg-character-sheet.html
- templates/items/ffg-criticaldamage-sheet.html
- templates/items/ffg-criticalinjury-sheet.html
- templates/parts/actor/ffg-criticalinjury.html
Fixed Adversary sheet to allow clicking on Criticals.
Refactored criticals to a partial.
> Updated Critical Damage and Injury sheets to allow modifiers.

- README.md
- modules/actors/actor-sheet-ffg.js
- modules/actors/adversary-sheet-ffg.js
- modules/helpers/actor-helpers.js
Updated function to handle new 7.1 formData structure.
> Refactored _updateObject function into new actor helper class

- README.md
- modules/helpers/actor-helpers.js
- modules/importer/import-helpers.js
Fixed error for no max property on character data.
> Fixed character import error for no force powers.

- README.md
- modules/helpers/item-helpers.js
- modules/importer/data-importer.js
- templates/parts/shared/ffg-modifiers.html
Fixed item sheet updates as they were broken with the new formData deep object.
Fixed issue with weapon stat modifiers
> Fixed Weapon Import ranges which was using a none standard field.

- README.md
- lang/en.json
- modules/importer/data-importer.js
- templates/importer/data-importer.html
Will import qualities as Journal Entries and attach them to weapons in specials area.
> Added Item Qualities to Oggdude Import.  

- README.md
- modules/actors/actor-ffg.js
- modules/actors/adversary-sheet-ffg.js
Updated minions, so that skills can be upgraded as non-squad minions.
> Applied same code from Character to Adversary sheet.

- README.md
- modules/actors/actor-ffg.js
- modules/helpers/actor-helpers.js
- modules/helpers/item-helpers.js
Fix issue with removing modifiers.
fixes #305
> Bug Fix #305 Defense autocalc was incorrectly adding upon save.

- README.md
- modules/importer/swa-importer.js
- modules/swffg-main.js
- templates/importer/swa-importer.html
NOTE: sw-adversaries data has typos, no descriptions, and no way to link to OggDude data without a data dictionary.  This will cause some issues if for example weapon skill is misspelled, it will not link correctly to the skill meaning the weapon rolling will not work.
fixes #189
> Import sw-adversaries

- README.md
- modules/actors/actor-ffg.js
- modules/helpers/actor-helpers.js
- modules/helpers/modifiers.js
- modules/swffg-config.js
- templates/parts/shared/ffg-modifiers.html
> Added Vehicle Modifiers (Only covers vehicle stats no pilot)

- README.md
- modules/actors/actor-ffg.js
- modules/helpers/actor-helpers.js
Fix for "handling" on vehicles.
> 0.7.2 Update (obj.isPC replaced with obj.hasPlayerOwner).

- README.md
- modules/actors/actor-sheet-ffg.js
- modules/actors/adversary-sheet-ffg.js
setProperty does not initialize variable as object anymore, need to explicitly initialize as an empty object.
> Fixed issue with creating new skill.

- README.md
- templates/parts/actor/ffg-skills.html
The issue was when I added dynamic skill groups, forgot to update reference to actor type.
> Fixed issue with Minion group skills.

- README.md
- modules/helpers/actor-helpers.js
Issue was from flags not existing by default on minion sheet, and specific flag would never exist.
> Fixed issue with minion sheet erroring.

- modules/swffg-main.js
This change, on top of dsn v3 alpha 7 will let users change any values that aren't specified in the colorset.
> Fix to let users customize their dice a bit more

- modules/swffg-main.js
- styles/starwarsffg.css
Per discussion in the Discord, this is my set of changes that enable a UI-based destiny point display.  No check currently for GM permissions; just errors for people without permission to do game.settings.set().
> Added UI display of destiny points

- README.md
- lang/en.json
> Renamed Hull Strain to Sys Strain in en.json

- README.md
- scss/starwarsffg.scss
- styles/starwarsffg.css
- templates/chat/item-card.html
> enhancement 405, added images to the send to chat feature.

- README.md
- modules/actors/actor-sheet-ffg.js
- modules/helpers/actor-helpers.js
- templates/parts/shared/ffg-block.html
> Added comma display for credits.

- modules/helpers/actor-helpers.js
This fixes the issue for vehicles, as they don't have credits.
> fixed issue with saving when credits are not available (like on minions)

- README.md
- modules/actors/actor-ffg.js
Fixes #419 
This will cause issues with 0.5 characters that were migrated.
> Fixed bug where brawn and willpower were not be added correctly to wounds and strain

- README.md
- modules/actors/actor-ffg.js
- modules/actors/actor-sheet-ffg.js
- scss/components/_sheet_base.scss
- styles/starwarsffg.css
- templates/parts/actor/ffg-weapon-armor-gear.html
From actor gear list, updated encumbrance calc to account for quantity.
Fixes #394
> Added increase/decrease gear quantity 

- README.md
- modules/actors/actor-sheet-ffg.js
- modules/helpers/macros.js
- templates/parts/actor/ffg-skills.html
> Enhancement 434 - Added drag-drop skills to macro bar.

- README.md
- modules/actors/actor-ffg.js
- modules/actors/actor-sheet-ffg.js
- modules/dice/pool.js
- modules/items/item-ffg.js
- modules/items/item-sheet-ffg.js
- modules/popout-editor.js
> Enhancement 453

- README.md
- modules/dice/pool.js
- modules/dice/roll.js
- modules/helpers/dice-helpers.js
- modules/swffg-config.js
- templates/dice/roll-ffg.html
- templates/roll-options.html
Updated code for Force Die only rolls to exclude success/failure message.
> Added Light and Dark side additions to rolls.

- README.md
- lang/en.json
- modules/actors/actor-sheet-ffg.js
- modules/actors/adversary-sheet-ffg.js
- modules/helpers/partial-templates.js
- modules/items/item-ffg.js
- scss/components/_dicepool.scss
- scss/components/_tooltip.scss
- styles/starwarsffg.css
- templates/chat/force-power-card.html
- templates/chat/roll-forcepower-card.html
- templates/chat/roll-weapon-card.html
- templates/dice/roll-ffg.html
- templates/parts/actor/ffg-forcepowers.html
> Enhancement 396

- README.md
- modules/combat-ffg.js
- package-lock.json
- package.json
- scss/components/_initiative_dialog.scss
- styles/starwarsffg.css
- templates/dialogs/ffg-initiative.html
> Added Boost/Setback/Failure/Threat to initiative dialog.

- README.md
- lang/en.json
- modules/ffg-destiny-tracker.js
- scss/components/_destiny_ui.scss
- styles/starwarsffg.css
Right click on top/bottom destiny pool bar as GM to send a Roll chat message.
Players can click on roll button in chat to roll destiny.
Fixes #433
> Enhancement 433 - Added rolling for Destiny Pool.

- README.md
- modules/swffg-main.js
> Added hook on chat message rendering to handle dice symbol replacement

- README.md
- modules/importer/data-importer.js
- modules/importer/import-helpers.js
> Enhancement 484

- README.md
- templates/parts/actor/ffg-weapon-armor-gear.html
> Enhancement 486 - Add quantity management to vehicle cargo hold items.

- README.md
- modules/groupmanager-ffg.js
- modules/swffg-main.js
Switched groupmanager to canvaslayer to avoid token layer issue of display all associated object.
fixes #444
> Fix 444 - Fixed issue with Group Manager access being lost.

- README.md
- modules/actors/actor-sheet-ffg.js
- modules/helpers/actor-helpers.js
Added Enable/Disable Auto Soak Calculation on Character and Minion sheets.
Fixes #506
> Enhancement 506

- README.md
- lang/en.json
- modules/actors/actor-ffg.js
- modules/actors/actor-sheet-ffg.js
- scss/components/_charactersheet.scss
- styles/starwarsffg.css
- templates/actors/ffg-character-sheet.html
- templates/parts/shared/ffg-block.html
Added general data area (accessed by clicking id-badge icon underneath Specializations).  
The general area has valid general information for a character based on dice theme (genesys has strength/flaw/desire/fear and star wars has motivations).  
Obligation/Duty/Morality area can be accessed by clicking on the header of the item on the biography section. 
Fixes #403
> Enhancement 403

- scss/components/_forcepowers.scss
- styles/starwarsffg.css
- templates/parts/actor/ffg-forcepowers.html
> Reverted force power list on Character sheet to table.

- scss/components/_charactersheet.scss
- styles/starwarsffg.css
Fixed formatting in those text areas.
> Updated sizing for emotional strengths and weaknesses.

- README.md
- lang/en.json
- modules/importer/swa-importer.js
- templates/importer/swa-importer.html
Enhanced current SWA Importer to create compendiums for non-starwars files based on filename (http://genesysadversaries.dylanpetrusma.com/).
> Added ability to import swa formated data

- README.md
- modules/importer/data-importer.js
- templates/importer/data-importer.html
(NOTE!!! We will be able to link the skill descriptions to the skill on the character sheet.)
> Enhancement 518 - Added OggDude Import of Skill Descriptions and JournalEntries

- README.md
- modules/helpers/common.js
- modules/importer/import-helpers.js
Added try..catch to character portrait upload.
> Added missing class to ForgeUploadFile call.

- README.md
- scss/components/_charactersheet.scss
- styles/starwarsffg.css
- templates/parts/actor/ffg-criticalinjury.html
- templates/parts/actor/ffg-forcepowers.html
- templates/parts/actor/ffg-signatureability.html
- templates/parts/actor/ffg-weapon-armor-gear.html
Fixed issue with v2 styles cutting off.  
Fixed issue with Signature Abilities and Force Power Upgrades not being listed (from previous core update)
> Fix v2 styles

- README.md
- modules/actors/actor-sheet-ffg.js
- modules/swffg-main.js
- scss/components/_charactersheet.scss
- styles/starwarsffg.css
- templates/actors/ffg-character-sheet.html
Fixed styling issue with v2 sheet.
Fixes #539
> Fixed issue where added skills were removed when duplicating an actor.

- modules/swffg-main.js
- scss/components/_charactersheet.scss
- styles/starwarsffg.css
> Fix alt skill list applying to new character.

- README.md
- modules/importer/data-importer.js
- modules/importer/import-helpers.js
> Added `Source` to the description for all imported items.

- modules/actors/actor-ffg.js
- modules/swffg-main.js
Add support for grouping talents by activation type (#504)
Note that this is English only. I don't speak the other languages, sorry.
> add support for grouping talents

- modules/actors/actor-sheet-ffg.js
- modules/swffg-main.js
> Fixed group skill values when duplicating a character.

- templates/parts/actor/ffg-weapon-armor-gear.html
Display restricted items (#596)
> display restricted items in red with a tooltip

- modules/actors/actor-ffg.js
> typo in vehicle

- README.md
- modules/items/item-ffg.js
- modules/swffg-main.js
- scss/components/_items.scss
- styles/starwarsffg.css
> Enhancement 633

- README.md
- lang/en.json
- modules/config/ffg-dice.js
- modules/settings/settings-helpers.js
- modules/swffg-config.js
- modules/swffg-main.js
- styles/mandar.css
- system.json
> Enhancement 646

- README.md
- modules/dice/roll-builder.js
- system.json
Added saving sound path on item roll (ie Weapons)
Fixes #672
> Enhancement 672 - Added saving sound path on item roll (ie Weapons)

- modules/groupmanager-ffg.js
Add Group to Combat will no longer create multiple encounters, also all
player tokens and selected tokens will only be added once to the combat
initiative. Clicking add group again will no longer remove any
combatants from the encounter
> Fix Group Manager Add Group To Combat Function

- modules/importer/import-helpers.js
- modules/importer/swa-importer.js
- system.json
Fixed issue with career skill parsing.
> Fixed regex issue where finding SWA quality description was not working.

- lang/en.json
- modules/groupmanager-ffg.js
- modules/settings/settings-helpers.js
Adds a toggle to system settings to hide/show the results from
Obligation, Duty, and eventually Morality rolls
> Add privacy toggle to group manager table rolls

- modules/groupmanager-ffg.js
Replace actor name with an entity link on all obligation and duty rolls
> Add actor chat link to obligation roll

- README.md
- modules/items/item-sheet-ffg.js
> Fixed issue with available hardpoint calculation.

- README.md
- modules/importer/import-helpers.js
> Reimporting was causing duplicate modifiers.

- README.md
- modules/importer/import-helpers.js
> Fixed issue where additional modifiers were being incorrectly added.

- README.md
- lang/en.json
- modules/dice/pool.js
- modules/dice/roll.js
- system.json
- templates/dice/roll-options-ffg.html
> added triumph and despair to die roller.

- README.md
- modules/actors/actor-sheet-ffg.js
- modules/helpers/dice-helpers.js
- system.json
Fixed issue with damaged weapon rolls.
> Fixed issue with opening character sheet.

- modules/groupmanager-ffg.js
There were a few bugs about rolling initiative and toggling combat after
adding a group to initiative in Group Manager. This addresses those
issues by adding the group in a single batch.
> Fix Add Group to Combat

- README.md
- modules/helpers/embeddeditem-helpers.js
- modules/items/item-ffg.js
- modules/items/item-sheet-ffg.js
- modules/items/itembase-ffg.js
> Fix 759 - Fixed issue where unable to add modifiers to item attachments.

- README.md
- modules/groupmanager-ffg.js
> Fix 773 - Fixed issue with Obligation/Duty table on GroupManager

- README.md
- templates/actors/ffg-character-sheet.html
> Fix 774 - Fixed issue where setting characteristic to 0 was not setting the value to 0.

- modules/helpers/embeddeditem-helpers.js
- modules/items/item-ffg.js
- modules/items/item-sheet-ffg.js
- modules/items/itembase-ffg.js
- system.json
First part of removing on the fly creation of attachments/qualities.
> Remove on the fly

- styles/mandar.css
Sorry for dual merge, I hadn't seen this fix before 😅
> Fix Injury position on mandar.css

- README.md
- modules/actors/actor-ffg.js
- modules/helpers/dice-helpers.js
- modules/swffg-main.js
> Fix 795 - Fixed issue where custom one-off skills disappear on refresh.

- modules/actors/actor-ffg.js
> revert minion code to correctly reduce numbers.

- README.md
- modules/helpers/actor-helpers.js
> Updated RegEx for monetary value scrubbing to allow Safari.

- README.md
- templates/parts/shared/ffg-block.html
> Fixed issue where "block" values were incorrectly specifying data type.

- modules/actors/adversary-sheet-ffg.js
Adversary sheet options were missing checkboxes.
> Add in checkboxes for adversary options.

- lang/en.json
- modules/config/ffg-ranges.js
- modules/settings/settings-helpers.js
- modules/swffg-config.js
- modules/swffg-main.js
Allows switching between Genesys and Star Wars range bands in the system settings. #801
> Add toggle for Genesys vehicle range bands

- modules/actors/actor-ffg.js
- modules/config/ffg-armor.js
- modules/config/ffg-modifiers.js
- modules/helpers/modifiers.js
- modules/items/item-ffg.js
- modules/items/item-sheet-ffg.js
- styles/starwarsffg.css
- templates/items/ffg-armour-sheet.html
- templates/parts/actor/ffg-weapon-armor-gear.html
- templates/parts/shared/ffg-modifiers.html
#874 Can now add item modifiers and attachments to armors
> Allow item mods/attachments on armor

- modules/helpers/dice-helpers.js
Issue with the Token Action HUD #848
Also some formatting fixes.
> Make sure skill name is defined

- modules/config/ffg-weapons.js
- modules/helpers/modifiers.js
- modules/items/item-ffg.js
- modules/items/item-sheet-ffg.js
- scss/components/_itemarmorsheet.scss
- styles/starwarsffg.css
- templates/items/ffg-armour-sheet.html
- templates/items/ffg-weapon-sheet.html
- templates/parts/actor/ffg-weapon-armor-gear.html
- templates/parts/shared/ffg-block.html
Includes some formatting for armor, modifier and attachment sheets. #719
> Weapon mods and attachment fixes

- modules/items/item-ffg.js
- modules/items/item-sheet-ffg.js
- scss/components/_itemvehicleweaponsheet.scss
- styles/starwarsffg.css
- templates/items/ffg-shipweapon-sheet.html
- templates/parts/actor/ffg-weapon-armor-gear.html
Also makes sure the vehicle sheet shows adjusted values. Addresses issue #849
> Weapon Mods can be added to Vehicle Weapons

- templates/chat/roll-weapon-card.html
- templates/items/ffg-shipweapon-sheet.html
- templates/items/ffg-weapon-sheet.html
Displays note for weapon rolls in the roll card.
> Weapon Roll note

- modules/helpers/modifiers.js
- modules/importer/oggdude/importers/weapons.js
- modules/items/item-ffg.js
- templates/items/ffg-weapon-sheet.html
- templates/parts/shared/ffg-block.html
Covers cases such as Aeffects, Selonian Tail weapon, Realm of Terrinoth thrown weapons, etc... #808 and #804
> Allow use of any characteristic on any weapon

- modules/config/ffg-skillslist.js
Alchemy was using Willpower when it should be using Intellect.
> Update Alchemy to use Intellect

- modules/items/item-ffg.js
Completely missed this when adding the armor mods. Issue #929
> Adding in item attachment calculation

- modules/helpers/common.js
Compendiums changed a bit so this retrieves correctly now. Had an error when trying to open up the referenced talent from the specialization sheet.
> New compendium changes

- lang/de.json
- lang/en.json
- lang/es.json
- lang/fr.json
- modules/ffg-destiny-tracker.js
When a point is flipped, it was not localized. #953
> Adding translation for destiny chat

- modules/actors/actor-ffg.js
fixed actor specific skills being filled with all skills resulting in Blank skills being added 
Fixes Issue #941
> Bugfix 941 Empty Skills

- lang/en.json
- lang/es.json
- lang/fr.json
- modules/config/ffg-modifiers.js
- modules/helpers/modifiers.js
Adds a Roll Mod to "Remove Setback" (issue #916)
> Add Remove Setback as Roll Mod

- lang/en.json
- lang/es.json
- lang/fr.json
- modules/config/ffg-modifiers.js
- modules/helpers/modifiers.js
- modules/importer/import-helpers.js
- modules/settings/settings-helpers.js
- modules/settings/ui-settings.js
- package-lock.json
- templates/chat/force-power-card.html
- templates/chat/item-card.html
- templates/chat/roll-forcepower-card.html
- templates/chat/roll-weapon-card.html
Getting rid of the dev branch. It's an unnecessary abstraction.
We handle releases via tagging anyway so a separate dev branch is just an inconvenience and master hasn't been sacrosanct / stable for a while due to various wild PRs emerging.
> Merge dev to master - dev is going bye-bye

- package-lock.json
- package.json
- templates/actors/ffg-character-sheet.html
By adding newlines back in and removing the commit hook that kills them off with prettier.
We don't need to use prettier. Just write pretty code.
Also means we can remove a bunch of unnecessary dependencies from package.json.
> Restore readability to ffg-character-sheet.html

- modules/actors/actor-ffg.js
- modules/actors/actor-sheet-ffg.js
- modules/swffg-main.js
Fixes issues with newly created Star Wars characters
Fixes display of custom skill lists
Allows switching between skill lists in system settings without breaking existing characters.
> Fix Star Wars and Custom skill list behaviour

- modules/combat-ffg.js
resolves: https://github.com/StarWarsFoundryVTT/StarWarsFFG/issues/988
Fixed initiative not being rollable
> fixed broken initiative for v9

- modules/importer/swa-importer.js
* properly imports ranks
* re-importing will now update previously-imported data
should fix #1001
> fix(swa importer): fix importer

- modules/helpers/macros.js
> fix(macro): fix drag-and-drop item macro creation

- styles/mandar.css
> Realign tabs vertically on mandar actor sheet v2

- modules/helpers/flag-migration-helpers.js
- modules/swffg-main.js
Migrate all old flags to new system scope "starwarsffg" for items, actors
> Migrate old flags to new system scope for old worlds

- modules/dice/roll.js
> fix(qualities): don't break rolls with new change

- modules/items/item-ffg.js
> Fix compendiums nested in items

- modules/dice/roll.js
- templates/chat/roll-weapon-card.html
* checks if the adjusted damage is 0 and uses the value instead if it is
fixes #926
> fix(damage): hack to display correct damage values

- styles/mandar.css
Fixes https://github.com/StarWarsFoundryVTT/StarWarsFFG/issues/1025
> Remove mandar checkbox formatting for Foundry settings

- modules/groupmanager-ffg.js
Fixes https://github.com/StarWarsFoundryVTT/StarWarsFFG/issues/1032
> Wait for group mgr rolls to evaluate before creating chat message

- modules/ffg-destiny-tracker.js
- scss/components/_destiny_ui.scss
- scss/components/_groupmanager.scss
- styles/starwarsffg.css
- templates/ffg-destiny-tracker.html
This removes the dropdown from the destiny tracker but just puts the buttons directly in the tracker for easy access.
> Fix for #906

- modules/ffg-destiny-tracker.js
Mac users are people too... mostly
> Handle Mac OSX CMD key in destiny tracker

- scss/components/_actorsheet_base.scss
- scss/components/_itemsheet_base.scss
- styles/starwarsffg.css
Fix https://github.com/StarWarsFoundryVTT/StarWarsFFG/issues/1043
> Fix sheet styling issue caused by Foundry v9.245

- modules/actors/actor-sheet-ffg.js
- templates/parts/actor/ffg-weapon-armor-gear.html
Can add weapons, armor, gear, ship weapons and ship attachments directly to a character or vehicle. #612
> Allows adding items directly to a character

- modules/helpers/dice-helpers.js
* macros no longer use "data" calls
* macros properly pull item data
#1081
> fix(v10): fix macros

- templates/parts/ffg-paused.html
> fix(v10): fix pause screen

- modules/importer/skills-list-importer.js
- modules/swffg-main.js
* skill lists can now be imported
* the world now reloads to pick up the new skill list so it can be set
#1081
> fix(v10): fix skill list interaction

- modules/actors/actor-sheet-ffg.js
- modules/helpers/embeddeditem-helpers.js
- modules/helpers/modifiers.js
- modules/importer/import-helpers.js
- modules/swffg-main.js
work on importers of all types. no known importer issues remain, though there is a shift in functionality - existing actors are now created with a new name instead of being updated
#1081
> V10 actor import

- modules/actors/actor-sheet-ffg.js
- templates/parts/actor/ffg-criticalinjury.html
* fix critical injuries and damage not being able to be applied to actors
#1092
> fix(v10): crits

- modules/actors/actor-ffg.js
- templates/items/ffg-shipweapon-sheet.html
- templates/items/ffg-weapon-sheet.html
* correct typo in encumbrance on sheets (will require re-entering data on any items touched while this bug was in place)
* correct item enumeration for Foundry v10
#1097
> fix(v10): encumbrance

- modules/dice/roll-builder.js
- modules/dice/roll.js
- modules/items/item-ffg.js
- templates/chat/roll-weapon-card.html
* fix console error when updating an item
* fix qualities not properly hyperlinking, hopefully without breaking other qualities
> V10 item qualities

- modules/swffg-main.js
warn on load of alpha version (warns every load)
> feat(v10): show a warning on alpha versions of the system

- templates/chat/roll-weapon-card.html
Changing from data to system so the rank displays in the weapon card in the chat.
> Quality Rank Display

- modules/swffg-main.js
fix contributed by `prolice` on Discord
> fix(mandar): fix Mandar theme in Forge

- modules/helpers/item-helpers.js
- modules/items/item-sheet-ffg.js
> fix(items): fix inability to add qualities from compendiums

- modules/helpers/actor-helpers.js
- templates/popout-editor.html
#1118
despite the diff showing a giant line of text, it's a single if statement and a lot of tabbed content
line 8 added:
```javascript
// as of Foundry v10, saving an editor only submits the single entry for that editor
if (Object.keys(formData).length > 1) {
} // end of the update block
```
> fix(editor): fix popout editor

- modules/helpers/modifiers.js
> fix(specializations): apply mods from specializations

- modules/dice/roll-builder.js
whoops I didn't test enough to realize this broke skill rolls
> fix(roll): correct skill rolls

- modules/swffg-main.js
https://github.com/StarWarsFoundryVTT/StarWarsFFG/issues/1129
> Fix #1129 NPE

- modules/actors/actor-ffg.js
- modules/actors/actor-sheet-ffg.js
- modules/helpers/actor-helpers.js
Missing some `starwarsffg?.` from some checks. #1131
> Points AutoSoak to correct flag

- modules/dice/roll-builder.js
sorry for the bad commit message, I assumed my IDE kept the git commit after it failed the first time.
fix for the chat-based roll builder not working
> fix(roll): fix roll builder

- modules/swffg-main.js
- scss/components/_charactersheet.scss
- styles/starwarsffg.css
- templates/actors/ffg-character-sheet.html
Fix for #923
Added notes on Character sheet to indicate Drag/Drop
Added #each_when to allow for easier filtering and optional "else" clause when no values match.
My first PR for the project, let me know if I need to make any changes!
> Added notes on Character sheet to indicate Drag/Drop functionality #923

- templates/actors/ffg-adversary-sheet.html
Follow up to previous commit adding notes to Character sheet. See issue #923 and PR #1140
> Update Adversary Sheet to show Drag Here note

- styles/mandar.css
add styling to mandar theme as well
> fix(style): add drag styling for Mandar theme

- lang/en.json
- modules/actors/actor-sheet-ffg.js
- modules/helpers/crew.js
- modules/helpers/dice-helpers.js
- modules/swffg-main.js
- templates/parts/actor/ffg-weapon-armor-gear.html
add drag-and-drop support for crew members on a ship
* I did not add non-English translations
* no known issues, though some of the code may be questionable (please keep me honest with the implementation)
> V10 vehicle crew

- scss/components/_tooltip.scss
- styles/starwarsffg.css
> Fix hover issue on skill dice

- lang/en.json
- modules/actors/actor-ffg.js
- modules/config/ffg-modifiers.js
- modules/dice/pool.js
- modules/helpers/dice-helpers.js
- templates/parts/shared/ffg-modifiers.html
Implementing feature request #922
Needs translations for `SWFFG.ModTypeSkillAddUpgrade`
> Add "Skill Add Upgrade" ModType

- modules/helpers/embeddeditem-helpers.js
- modules/importer/swa-importer.js
- modules/items/item-ffg.js
Fix ItemModifier imports from SWA and now displays journal entry instead of error message when clicked on.
Fix for #1139
Tested with Genesys dataset
> Fix ItemModifier imports from SWA

- modules/actors/actor-sheet-ffg.js
- modules/swffg-main.js
- scss/components/_forcepowers.scss
- styles/starwarsffg.css
- templates/actors/ffg-adversary-sheet.html
- templates/actors/ffg-character-sheet.html
- templates/actors/ffg-minion-sheet.html
- templates/parts/actor/ffg-forcepowers.html
Abilities weren't showing at all. And Force Powers were always showing.
Changed Force Powers to use the same logic as Signature Abilities and fixed an issue with the #contains helper
> Fixed issue with Signature Abilities and Force Powers displaying

- modules/combat-ffg.js
Fix for error when rolling all or rolling all NPCs
> Fix for "rolling all..." on combat

- modules/dice/roll-builder.js
> Fix the sound on rolls

- modules/importer/swa-importer.js
Fix for #1160
Rewrote _enableImportSelection to _getFilePaths as SWA doesn't have import selection checkboxes. 
If multiple files are found the system will use the one with '/src/' in the path. 
If it can't find a resolution it will show a UI error.
> Fix SWA Adversary importer when multiple copies of needed files are found

- lang/en.json
- modules/actors/actor-sheet-ffg.js
- modules/helpers/partial-templates.js
- modules/items/item-sheet-ffg.js
- template.json
- templates/actors/ffg-adversary-sheet.html
- templates/actors/ffg-character-sheet.html
- templates/actors/ffg-minion-sheet.html
- templates/items/ffg-ability-sheet.html
- templates/parts/actor/ffg-abilities.html
Can create Abilities and drop them onto character sheets for easy duplication of adversary/character abilities
> Adding Drag and Drop Abilities

- modules/dice/roll.js
> Add a check for rolls that have no terms.

- modules/swffg-main.js
* should fix hyperlinked vehicle weapon qualities
> fix(vehicle): include vehicle weapons in the port logic

- modules/dice/roll-builder.js
> fix(roller): fix chat roller not working

- templates/items/ffg-specialization-sheet.html
As described here: https://github.com/StarWarsFoundryVTT/StarWarsFFG/issues/1188
> Fix specialisation edit actions being hidden on imported specs

- modules/items/item-sheet-ffg.js
Also use `uuid` better in itemsheet dragDrop events in general.
See https://github.com/StarWarsFoundryVTT/StarWarsFFG/issues/1109 for more details
> Fix inconsistencies with talent items dropped on specialisation sheets

- modules/swffg-main.js
* correct inability to load PDFs in journals
* correct dice sometimes not rendering properly
#1202, #1189
> fix(journal): multiple fixes

- modules/items/item-sheet-ffg.js
* duplicates the item so we can assign an ID
#1211
> fix(item): fix item quality error

- modules/items/item-ffg.js
* correct applies the update performed during item initialization
#1203
> fix(item): fix for custom force powers

- modules/helpers/modifiers.js
Noticed an issue that encumbrance modifiers weren't getting multiplied by quantity.
> Multiply by Quantity

- modules/actors/adversary-sheet-ffg.js
Adding the option to remove strain for adversaries that should have already been added.
> Remove Strain for adversaries

- modules/groupmanager-ffg.js
Testing user permission now available under different Actor method
Fixes #1213
> Fix group manager for Foundry v10

- modules/actors/actor-sheet-ffg.js
Fixes #864
Based on work by @basicgm in https://github.com/StarWarsFoundryVTT/StarWarsFFG/issues/864#issuecomment-812760684
> Sort Actor skill list based on locale rules

- modules/importer/skills-list-importer.js
Adding a try/catch when importing.
> Adding error for skill importer

- modules/settings/crew-settings.js
- modules/settings/ui-settings.js
- templates/dialogs/ffg-ui-settings.html
`setting.module` doesn't appear to be valid in the current Foundry API
> Should use setting.namespace instead of setting.module

- modules/ffg-destiny-tracker.js
* overwrites destiny menu close function to toggle the normal escape menu
#1026
> fix(esc): fix for escape button being blocked by destiny menu

- modules/ffg-destiny-tracker.js
> fix(destiny): only roll destiny once, regardless of GM count

- templates/actors/ffg-minion-sheet.html
- templates/actors/ffg-vehicle-sheet.html
> fix(ownership): limit displayed info for limited-view actors

- lang/en.json
- template.json
- templates/actors/ffg-vehicle-sheet.html
* add a toggleable navicomputer to vehicles
#1164
> feat(vehicles): add navicomputer

- README.md
Updating the Discord invite so it isn't invalid.
> Update Discord invite in README.md

- templates/actors/ffg-adversary-sheet.html
* properly hides strain if disabled in sheet options
#1276
> fix(adversary): fix strain display

- modules/items/item-sheet-ffg.js
- templates/items/ffg-specialization-sheet.html
* you can now set the image for specializations
#892
> feat(specialization): allow setting image

- lang/en.json
- styles/starwarsffg.css
- template.json
- templates/items/ffg-forcepower-sheet.html
* force powers now include a force rating field (which defaults to 0)
#897
> feat(force-power): add required FR field

- modules/actors/actor-sheet-ffg.js
- modules/helpers/crew.js
- templates/parts/actor/ffg-weapon-armor-gear.html
* shows crew member dice rolls in vehicle sheet
#1281
> feat(crew): add crew dice pool to vehicle

- modules/helpers/actor-helpers.js
> fix(minions): remove rank added when granting group skill

- modules/actors/actor-sheet-ffg.js
- modules/helpers/dice-helpers.js
* now collects modifiers from item attachments on ship weapons
#1285
> fix(vehicles): fix dice pool for vehicle weapons

- modules/items/itembase-ffg.js
* fix inability to update force powers
* I _think_ they were broken because if you submit "system" in the formData, foundry doesn't look for "data" anymore... and the new field submits "system", so we were losing any other changes
> fix(force_powers): fix updating FPs

- template.json
- templates/items/ffg-forcepower-sheet.html
* force powers now include a base power cost
#1304
> feat(force_powers): add base power cost

- modules/helpers/dice-helpers.js
* fix incorrect skill name lookup in non-English games
#1308
> fix(crew): fix crew not handling localizations

- modules/helpers/crew.js
* fix for my function rewrite breaking opening vehicles where a crew member has been deleted
#1306
> fix(crew): fix deleted crew not being removed

- modules/actors/actor-sheet-ffg.js
- templates/parts/actor/ffg-weapon-armor-gear.html
* writes each part of the crew info to a dedicated attribute instead of sharing and splitting
#1302
> fix(crew): fix crew with dashes

- modules/helpers/crew.js
* correctly checks if the dropped actor is a vehicle or not and bails if it is
#1312
> fix(crew): fix ship-on-ship action

- modules/actors/actor-sheet-ffg.js
- modules/helpers/crew.js
- templates/parts/actor/ffg-weapon-armor-gear.html
* add ability to open crew from vehicle sheet
#1284
> feat(crew): open actor sheet from crew view

- lang/en.json
- styles/mandar.css
- styles/starwarsffg.css
- templates/parts/actor/ffg-weapon-armor-gear.html
* move crew roll into a different column
#1305
> refactor(crew): move crew roll into new column

- scss/components/_dicepool.scss
- scss/components/_forcepowers.scss
- scss/components/_itemcriticalinjurysheet.scss
- scss/components/_itemgearsheet.scss
- scss/components/_vehiclesheet.scss
- styles/starwarsffg.css
* port all manual CSS changes to SCSS files
* apparently removes some trailing whitespace since my IDE is configured to strip it
#1300
> refactor(css): backport CSS changes to SCSS

- lang/en.json
- modules/actors/actor-sheet-ffg.js
- scss/components/_charactersheet.scss
- styles/mandar.css
- styles/starwarsffg.css
- templates/actors/ffg-adversary-sheet.html
- templates/actors/ffg-character-sheet.html
* moves force powers and specializations into the section with species, career, and specialization for characters and adversaries
#713
> refactor(actor): update top-level info

- modules/helpers/actor-helpers.js
* update formData to include current minion count
* this permits automation tools to use the minion count
> Minion update 1060

- lang/en.json
- modules/combat-ffg.js
- scss/components/_combat_tracker.scss
- styles/mandar.css
- styles/starwarsffg.css
- templates/dialogs/combat-tracker.html
* custom combat tracker now shows which actors have gone -and have yet to go- each round
#1333
> feat(combat): track actors

- scss/components/_forcepowers.scss
- styles/starwarsffg.css
* cost now has a background in both themes
#1325
> style: fix force power cost

- modules/ffg-destiny-tracker.js
* properly looks for a single GM
closes #1332
> fix: destiny pool with >1 GM

- lang/en.json
* update the description of the "generic slots" setting to make it more clear what it controls
closes #1346
> docs: clarify setting

- lang/en.json
- modules/actors/actor-sheet-ffg.js
- modules/combat-ffg.js
- modules/helpers/crew.js
- modules/settings/crew-settings.js
- modules/swffg-main.js
- templates/dialogs/crew-settings.html
* adds a new (configurable) role for vehicle crew members
* when vehicles have this crew role assigned, initiative for that vehicle will be rolled with the crew member's skill
closes #1317
> feat(combat): add vehicle support

- modules/popout-editor.js
> popout-editor - fix unresizable window

- modules/importer/import-helpers.js
* correct bug for >1 specialization, >1 force power
#1348
> fix(importer): handle more than one specialization

- styles/mandar.css
> fix(css): correct height bug in mandar v2 sheets

- styles/mandar.css
- templates/dialogs/combat-tracker.html
* actor tracker at the top of the combat tracker now shows defeated actors
#1374
> feat(combat): show defeated enemies

- modules/actors/actor-sheet-ffg.js
- modules/items/item-ffg.js
- modules/swffg-main.js
* properly escapes content and loads it
#1385
> fix(items): fix item qualities on items

- modules/items/item-ffg.js
> fix(items): correct opening items with blank qualities

- styles/mandar.css
> fix(rolls): fix for giant dice again

- modules/helpers/macros.js
- modules/swffg-main.js
* macros now capture the image of the document they came from
* you can now create display macros for all item types
#1389
> refactor(macros): macro improvements

- modules/swffg-main.js
* uses activeGM instead of trying to find one
#1388
> fix(gm): correct GM detection

- modules/helpers/crew.js
- modules/helpers/dice-helpers.js
* show remove setback dice on vehicle
* correct bug where handling was not included
#1380
> feat(crew): show remsetback

- modules/helpers/journal.js
> fix(dice): fix dice codes for genesys theme

- modules/config/ffg-dice.js
- modules/dice/pool.js
* now shows fixed results in roll pool
#1384
> feat(actors: show fixed results

- lang/en.json
- modules/combat-ffg.js
- templates/dialogs/ffg-initiative.html
* allow initiative roll upgrades
#1345
> feat(initiative): allow upgrades

- modules/config/ffg-modifiers.js
- modules/helpers/modifiers.js
- modules/items/item-sheet-ffg.js
- templates/parts/shared/ffg-modifiers.html
* allows setting defensive (melee and ranged) on item qualities
#840
> feat(defensive): allow stat mods for weapons

- modules/importer/oggdude/importers/item-attachments.js
- styles/mandar.css
* fixes created item type for ship attachments on import
* fixes sheet height for ship attachments
* fixes sheet height for vehicles
#1414
> fix(shipattachments): correct importer

- CHANGELOG.md
> docs(changelog): WIP 1.809 changelog

- modules/swffg-main.js
- modules/swffg-migration.js
- styles/mandar.css
- templates/notifications/new_version.html
* sends a one-time message when the system migrates versions
#1396
> feat(notification): update notification

- CHANGELOG.md
- modules/importer/import-helpers.js
* misc qualities are properly imported
#1169
> fix(importer): fix blank qualities

- CHANGELOG.md
- lang/en.json
- modules/actors/actor-ffg.js
- modules/actors/actor-sheet-ffg.js
- modules/config/ffg-characters.js
- modules/config/ffg-sheetdefaults.js
- modules/helpers/actor-helpers.js
- modules/helpers/token.js
- modules/importer/swa-importer.js
- modules/swffg-config.js
- modules/swffg-main.js
- styles/mandar.css
- template.json
- templates/actors/ffg-nemesis-sheet.html
- templates/actors/ffg-rival-sheet.html
* Adds the "nemesis" and "rival" actor types
* Updates importer to reference these
* Fixes a bug where adversary >6 fails to render on tokens properly
#1360
> feat(actors): add nemesis and rival

- modules/items/item-sheet-ffg.js
- styles/mandar.css
- templates/items/ffg-career-sheet.html
* detects if specializations / signature abilities linked in careers no longer exists and highlights them in red (if missing)
#1426
> feat(careers): show broken links

- modules/settings/settings-helpers.js
- modules/swffg-migration.js
> doc(theme): clearly denote default as unsupported

- styles/mandar.css
* extend weapon, armor, and gear max image width
#1439
> fix(css): raise item img max width

- CHANGELOG.md
- modules/importer/import-helpers.js
- modules/importer/oggdude/importers/careers.js
- modules/importer/oggdude/importers/item-attachments.js
- modules/importer/oggdude/importers/item-descriptors.js
- modules/importer/oggdude/importers/signature-abilities.js
- modules/importer/oggdude/importers/species.js
- modules/importer/swa-importer.js
- system.json
* introduces dedicated compendiums for various types of items
* further v12 fixes I missed originally
* moves compendiums to system-defined compendiums, as dynamically-defined ones did not work in my testing for v12
#1441
> feat(importer): dedicated compendiums

- CHANGELOG.md
- modules/importer/import-helpers.js
* fix for vehicle weapons being duplicated when re-running the importer
#1442
> feat(importer): vehicles

- CHANGELOG.md
- templates/parts/shared/ffg-block.html
* add XP log link to XP section
#1474
> feat(xp_log): xp log link

- CHANGELOG.md
- styles/mandar.css
* stops "special" field from overflowing
> Weapon special 1451

- lang/en.json
- styles/mandar.css
- templates/actors/ffg-character-sheet.html
- templates/actors/ffg-nemesis-sheet.html
- templates/actors/ffg-rival-sheet.html
* moves critial injuries to a dedicated tab (only in sheet v2)
#1472
> feat(crits): move crits to tab

- CHANGELOG.md
- templates/parts/actor/ffg-weapon-armor-gear.html
* show proper text for equipped/unequipped gear
* localize said text
#1469
> fix(equipped): fix equipped tooltip

- CHANGELOG.md
- modules/actors/actor-sheet-ffg.js
* remove skill purchase option from non-characters
#1477
> fix(actors): skill purchase

- CHANGELOG.md
- lang/en.json
- modules/actors/actor-sheet-ffg.js
- templates/dialogs/ffg-confirm-purchase.html
* check if user has appropriate force rating before allowing a purchase
#1452
> feat(xpSpending): force power

- CHANGELOG.md
- modules/swffg-main.js
> feat(sheets): v2 sheets default

- CHANGELOG.md
- modules/items/item-sheet-ffg.js
* fix for buying >1 talent not working
#1453
> fix(item_sheet): buy talents

- CHANGELOG.md
- lang/en.json
- modules/actors/actor-sheet-ffg.js
- modules/importer/oggdude/importers/species.js
- template.json
- templates/items/ffg-species-sheet.html
* add starting XP as a field in species
* update importer to include starting XP
* add starting XP to characters when they receive a species
#1459
> feat(species): starting XP

- CHANGELOG.md
- modules/combat-ffg.js
- templates/dialogs/combat-tracker.html
* fix a bug where actors claiming a slot not originally belonging to them prevented them from being removed from combat
* v12 testing 3 combat tracker fix
#1466
> fix(combat): combat tracker

- CHANGELOG.md
- lang/en.json
- modules/helpers/dice-helpers.js
- modules/swffg-main.js
* add per-client setting for including defense dice in default dice pool
#1355
> feat(combat): dice

- CHANGELOG.md
- modules/importer/oggdude/importers/species.js
- modules/items/item-sheet-ffg.js
- modules/swffg-main.js
- template.json
- templates/items/ffg-species-sheet.html
* Add the ability to define (and transfer) abilities on species
* Update importer to include abilities on species
* Transfer abilities to actor when it receives the species
* Minor improvement to how talents on species are displayed
#1461
> feat(species): abilities

- modules/swffg-main.js
* Update default compendiums in settings to match new naming scheme
#1516
> fix(settings): default compendiums

- CHANGELOG.md
- templates/actors/ffg-adversary-sheet.html
- templates/actors/ffg-character-sheet.html
- templates/actors/ffg-minion-sheet.html
- templates/actors/ffg-nemesis-sheet.html
- templates/actors/ffg-rival-sheet.html
* swapped the order of melee/ranged defense to match the books
#1471
> refactor(actors): defense

- styles/mandar.css
* make dice pool cursor a pointer
#1524
> feat(actors): skills

- styles/mandar.css
> style(actors): header

- CHANGELOG.md
- modules/helpers/crew.js
* refactor changelog to hopefully be more readable
* fix a bug where new crew logic did not work on a vehicle with no crew (classic)
#1524
> doc(changelog): refactor

- CHANGELOG.md
- modules/actors/actor-sheet-ffg.js
* fix directly added talents not showing
> fix(actor): talents

- modules/dice/roll.js
> fix(v12): dice

- CHANGELOG.md
- modules/actors/actor-sheet-ffg.js
* correct update call when changing skill characteristic
#1550
> fix(skills): change skill characteristic

- CHANGELOG.md
- modules/actors/actor-sheet-ffg.js
* add option to enable/disable force pool for rivals and nemesis
#1502
> feat(actors): FP for Rivals/Nemesis

- CHANGELOG.md
- modules/importer/oggdude/importers/skills.js
* correctly set journal content for skills
#1551
> fix(importer): skill descriptions

- CHANGELOG.md
- modules/actors/actor-ffg.js
- modules/actors/actor-sheet-ffg-v2.js
- modules/actors/actor-sheet-ffg.js
- modules/swffg-main.js
* properly calculate ranks of talents, regardless of source
* now shows talent source as "species"
#1540
> fix(species): fix species talents

- CHANGELOG.md
- modules/helpers/journal.js
- modules/importer/import-helpers.js
* correct bad text enrichers
* update importer sources to be on new lines instead of h4
#1559
> fix(text): fix disappearing text

- CHANGELOG.md
- system.json
* update system.json to use new format
#1538
> fix(system): v12 warnings

- CHANGELOG.md
- modules/helpers/dice-helpers.js
* fix weapon macros with enhancements module
https://github.com/wrycu/StarWarsFFG-Enhancements/issues/202
> fix(macros): weapon macros

- CHANGELOG.md
- lang/en.json
- modules/actors/actor-sheet-ffg.js
- templates/dialogs/ffg-confirm-purchase.html
* specializations and force powers are now grouped to be more legible
#1583
> feat(xp): group purchasables

- CHANGELOG.md
- lang/en.json
- modules/helpers/actor-helpers.js
- modules/swffg-main.js
* send message to GM when XP is spent
#1575
> feat(xp): notification

- CHANGELOG.md
- modules/helpers/actor-helpers.js
* manual edits now populate in the log
#1581
> feat(xp): log for manual edits

- CHANGELOG.md
- modules/actors/actor-sheet-ffg.js
* look at correct stat for purchasing force powers
#1584
> feat(xp): force power rating

- CHANGELOG.md
- styles/mandar.css
* raise max width to 500px
#1576
> fix(weapons): vehicle weapon width

- CHANGELOG.md
- modules/items/item-sheet-ffg.js
- styles/mandar.css
- templates/items/ffg-specialization-sheet.html
* talents added to specializations now have descriptions set again
#1573
> fix(talents): correct talent descriptions

- CHANGELOG.md
- modules/ffg-destiny-tracker.js
* correct destiny pool roll not populating in tracker
#1592
> fix(destiny): correct destiny pool roll

- CHANGELOG.md
- modules/items/item-sheet-ffg.js
* do not re-check talent details on every specialization load
#1593
> fix(specialization): loading time

- CHANGELOG.md
- modules/actors/actor-sheet-ffg.js
* exclude item boosts in characteristic cost
#1594
> fix(xp): characteristic cost

- CHANGELOG.md
- modules/items/item-sheet-ffg.js
- templates/items/ffg-weapon-sheet.html
* fix dice icons not rendering on "special" field of weapons
#1625
> fix(weapons): dice icons on special

- CHANGELOG.md
- lang/en.json
- modules/actors/actor-sheet-ffg.js
* prompt to spend XP on dropping a relevant item onto an actor
#1588
> feat(items): drag-and-drop XP spending

- CHANGELOG.md
- modules/helpers/crew.js
* use correct skill in non-star wars themes
#1597
> fix(crew): correct pilot role

- CHANGELOG.md
- modules/ffg-destiny-tracker.js
- styles/mandar.css
* dp flipping is now active
#1658
> theme(dp): theme destiny point flip

- modules/settings/settings-helpers.js
> refactor(settings): re-introduce clobbered setting

- CHANGELOG.md
This PR fixes an dangling CHANGELOG.md section and add some missing data (github issues links)
> chore(changelog): update and fix changelog

- CHANGELOG.md
- modules/importer/oggdude/importers/forcepowers.js
This PR fixes a basic force power mods not being imported from OggDude's Data.
Closes #1686
> fix(import): import basic force power mods

- .editorconfig
- CHANGELOG.md
This PR adds an [EditorConfig](https://editorconfig.org/) file with basic settings.
> feat(dev): add basic EditorConfig file

- CHANGELOG.md
- modules/actors/actor-sheet-ffg.js
> fix(xp): correct skill purchase

- CHANGELOG.md
- modules/helpers/dice-helpers.js
Allow to set challenge dices when create a dice pool.
> Allow to set challenge dices when create a dice pool.

- CHANGELOG.md
- modules/helpers/dice-helpers.js
Check status function can be used for shipweapon to change automatically the difficulty
> Shipweapon : Allow check for weapon status

- CHANGELOG.md
- modules/dice/roll.js
* fix for bug introduced (but not released) which prevented rolls using the FFG dice from resolving properly
* fox for blind GM roll not properly being hidden from player
#1712
> fix(rolls): rolling and blind rolling fixes

- CHANGELOG.md
- modules/ffg-destiny-tracker.js
- styles/mandar.css
- templates/ffg-destiny-tracker.html
> fix(storypoint): use Genesys story point when theme selected

- CHANGELOG.md
- modules/swffg-main.js
- modules/swffg-migration.js
- styles/mandar.css
- templates/notifications/empty_compendiums.html
> feat(compendiums): notify if all compendiums are empty

- CHANGELOG.md
- lang/en.json
- modules/importer/data-importer.js
- templates/importer/data-importer.html
> feat(importer): add select all button

- CHANGELOG.md
- modules/swffg-main.js
- templates/dialogs/ffg-sheet-options.html
- templates/group-manager.html
- templates/parts/shared/ffg-block.html
- templates/parts/shared/ffg-modifiers.html
> fix(template): stop using deprecated function

- CHANGELOG.md
- styles/mandar.css
- templates/items/ffg-shipweapon-sheet.html
- templates/items/ffg-weapon-sheet.html
> feat(weapons): move special field

- CHANGELOG.md
- modules/combat-ffg.js
- templates/dialogs/combat-tracker.html
> fix(combat): mouseover combatants now works properly

- CHANGELOG.md
- modules/combat-ffg.js
> fix(combat): don't spawn infinite combatants

- CHANGELOG.md
- modules/items/item-ffg.js
- modules/items/item-sheet-ffg.js
- modules/swffg-main.js
- styles/mandar.css
- templates/chat/item-card.html
- templates/chat/roll-forcepower-card.html
* remove clickable item pills when items are sent to chat
* instead, tooltips are used to display the information inline
* these tooltips are themed to match the system
> feat(chat): send-to-chat

- CHANGELOG.md
- modules/helpers/modifiers.js
* fix mods on attachments impacting the actor
#1768
> fix(items): attachments

- CHANGELOG.md
- modules/helpers/dice-helpers.js
* fix dice pool defaulting to empty average check sometimes
#1763
> fix(dice): dice pool

- CHANGELOG.md
- modules/actors/actor-ffg.js
> feat(stats): over threshold

- CHANGELOG.md
- lang/en.json
- modules/actors/actor-sheet-ffg.js
- styles/mandar.css
- templates/actors/ffg-character-sheet.html
* add button to manually adjust XP
#1630
> feat(xp): manual adjustment

- CHANGELOG.md
- modules/importer/import-helpers.js
* delete existing abilities when re-running the importer
#1721
> fix(species): do not reimport abilities

- CHANGELOG.md
- modules/actors/actor-sheet-ffg.js
- templates/actors/ffg-nemesis-sheet.html
* show bio in limited view; hide secret sections
#1774
> feat(nemesis): bio

- CHANGELOG.md
- modules/actors/actor-sheet-ffg.js
- templates/parts/actor/ffg-skills.html
* error if a default skill is being removed
#1571
> fix(skills): skill removal

- CHANGELOG.md
- system.json
* update version
* update changelog
* update download link
> chore(release): prep for 1.906 release

- CHANGELOG.md
- modules/items/item-sheet-ffg.js
* fix copying metadata from talents into the embedded version on specializations
#1805
> fix(talents): talent -> specialization drag-and-drop

- CHANGELOG.md
- styles/mandar.css
> fix(vehicles): image

- CHANGELOG.md
- modules/actors/actor-sheet-ffg.js
* correct default embedded names
#1815
> fix(items): embedded names

- CHANGELOG.md
- styles/mandar.css
* add scrolling to popout modifier window
#1824
> fix(modifiers): popout modifier

- modules/actors/actor-sheet-ffg.js
- templates/parts/actor/ffg-forcepowers.html
* correct overly broad roll selector
#1827
> feat(force_power): roll button

- CHANGELOG.md
- modules/actors/actor-sheet-ffg.js
- modules/importer/oggdude/importers/specializations.js
- template.json
- templates/dialogs/ffg-confirm-purchase.html
* add support for universal specializations
#1778
> feat(specializations): universal specs

- CHANGELOG.md
- lang/en.json
* update not enough XP msg to be generic
#1820
> fix(xp): not enough XP

- CHANGELOG.md
- modules/config/ffg-modifiers.js
- modules/importer/import-helpers.js
- modules/importer/oggdude/importers/item-descriptors.js
* add some dice mods on Oggdude import
#1836
> fix(importer): dice mods

- CHANGELOG.md
- lang/en.json
- modules/helpers/item-helpers.js
- modules/importer/oggdude/importers/careers.js
- modules/importer/oggdude/importers/specializations.js
- modules/items/item-ffg.js
- modules/items/item-sheet-ffg.js
- template.json
- templates/items/ffg-career-sheet.html
- templates/items/ffg-specialization-sheet.html
* add first-class support for career skills
* this does not add support for the selected rank. I may change my mind on this in the future
#1861
> feat(careerSkills): add career skills

- CHANGELOG.md
- modules/actors/actor-sheet-ffg.js
* prevent duplicate hook calls
#1818
> fix(actors): sheet hooks

- modules/actors/actor-ffg.js
- modules/items/item-ffg.js
- modules/items/item-sheet-ffg.js
- modules/swffg-migration.js
- templates/items/ffg-career-sheet.html
- templates/items/ffg-specialization-sheet.html
* ports existing worlds over to use AEs
#1855
> migrate(world): add AEs to existing worlds

- CHANGELOG.md
* clarify the addition of active effects
> doc(changelog): active effects

- CHANGELOG.md
- system.json
> release(1.907): prep for release

- CHANGELOG.md
- modules/swffg-migration.js
- system.json
* prep for 1.908 release
* fixes some migration errors
* handles errors to prevent the migration from failing to mark as complete
#1891
> release(1.908): prep for release

- CHANGELOG.md
- templates/actors/ffg-vehicle-sheet.html
* fixes editing defense, armor, and handling of vehicles when edit mode is enabled
#1896
> fix(vehicles): fix edit mode

- CHANGELOG.md
- modules/items/item-editor.js
* fix for mods on attachments on weapons being duplicated
#1838
> fix(items): mods

- CHANGELOG.md
- modules/actors/actor-ffg.js
* the size of the force dice pool is now dynamically read
#1890
> fix(AEs): force dice

- modules/actors/actor-sheet-ffg.js
- modules/items/item-sheet-ffg.js
hopefully fixes XP availability changing wildly when grants and purchases are mixed
> Xp confusion 1899

- CHANGELOG.md
- lang/en.json
- modules/settings/ui-settings.js
- modules/swffg-main.js
* add the ability for users to define additional statuses
#1941
> feat(statuses): user-defined statuses

- CHANGELOG.md
- modules/actors/actor-ffg.js
- modules/helpers/item-helpers.js
- modules/helpers/modifiers.js
* checks for skills existing before modifying them on actors
* improves attribute lookup on skills
* a previously-bugged world now migrates successfully
> fix(migration): improve migration logic

- CHANGELOG.md
- modules/importer/import-helpers.js
* apply characteristics to wounds + strain thresholds
#1955
> fix(importer): species

- CHANGELOG.md
- lang/en.json
- modules/importer/data-importer.js
- templates/importer/data-importer.html
* deletes compendiums when importing (can be disabled)
#1964
> feat(import): compendiums
