README.md, lang/en.json, modules/actors/actor-ffg.js, modules/actors/actor-sheet-ffg.js, modules/items/item-ffg.js, modules/items/item-sheet-ffg.js, scss/components/_forcepowers.scss, scss/components/_header.scss, scss/components/_specializations.scss, scss/components/_talents.scss, scss/starwarsffg.scss, styles/starwarsffg.css, template.json, templates/actors/ffg-character-sheet.html, templates/items/ffg-specialization-sheet.html
Added specializations, drag and drop talents onto specific node in the tree to add them, then like force powers, click the edit icon to enable talent path-ing.  
Clicking on the description box will open the talent that was dragged on, where you can edit the actually talent, not a copy attached to the specialization.
Add a specialization to a character by dragging and dropping it.  It will show up as a pill on the main screen.
In addition ALL ranks of the same talent will be summed and displayed in the list.  Clicking on the pill or the talent will open the specialization tree.
Non-owners will only be able to view the data, and only owners of the side-bar items (aka GMs) will be able to update talents from this interface.
=> Specializations

README.md, modules/items/item-sheet-ffg.js, scss/components/_itemarmorsheet.scss, scss/components/_itemgearsheet.scss, scss/components/_itemvehicleattachmentsheet.scss, scss/components/_itemvehicleweaponsheet.scss, scss/components/_sheet.scss, scss/components/_talentsheet.scss, styles/starwarsffg.css
Removed set height on item sheets to allow for core dynamic rendering mechanism to take over.  This should help with the localization issues on some item sheets.
=> Some Localization Rendering Fixes.

README.md, modules/actors/actor-ffg.js, modules/actors/actor-sheet-ffg.js, modules/items/item-ffg.js, modules/items/item-sheet-ffg.js, templates/items/ffg-specialization-sheet.html
The issue being that the talents are loaded AFTER the specializations, so for owned objects this causes an issue where the actual values have not been loaded yet, and the default values in the template.json are loaded.  I've figured out how to do a single initial load on the actor-sheet-ffg.js and updated the values there.  This should almost never be an issue unless changes are being made to talents after the specialization they are associated to have been added to a character.
=> Fix 2-way binding.  

README.md, modules/items/item-sheet-ffg.js, scss/components/_editor.scss, styles/starwarsffg.css, templates/items/ffg-forcepower-sheet.html, templates/items/ffg-shipweapon-sheet.html, templates/items/ffg-specialization-sheet.html, templates/items/ffg-weapon-sheet.html
fixes #126 
This changes the way the popout editor works, there will now be an edit button when hovering over a popout editor (like the normal editor).  Clicking that icon will launch the popout editor.
=> Fixes the popout editor from triggering when clicking embedded journal item.

README.md, template.json
second part of the fix.  This way when compendium items are imported the attributes object will be created.
fixes #155
=> Added attributes obect to forcepower and specializations items

README.md, modules/actors/actor-ffg.js, modules/actors/actor-sheet-ffg.js, modules/actors/adversary-sheet-ffg.js, modules/helpers/modifiers.js, modules/helpers/partial-templates.js, templates/actors/ffg-adversary-sheet.html, templates/actors/ffg-character-sheet.html, templates/parts/actor/ffg-forcepowers.html, templates/parts/actor/ffg-skills.html, templates/parts/actor/ffg-talents.html, templates/parts/actor/ffg-weapon-armor-gear.html, templates/parts/shared/ffg-modifiers.html
Added modifiers for Career Skills
Refactored character sheets using handlebar partials for skill, items, talents and force powers (shared with character and adversary sheets)
Added sheet options for Adversary for removing auto soak calculation (but only unlocks the soak field)
fixes #248
=> Modifiers careerskills

README.md, scss/components/_itemsheet_base.scss, styles/starwarsffg.css
CSS fix for item text not being displayed in editor correctly.
This also Fixes #162
=> Fix #162 and editor not displaying text in items.

README.md, modules/actors/actor-ffg.js, modules/actors/adversary-sheet-ffg.js, modules/helpers/actor-helpers.js
Fixed issue with soak calculation if auto calculation is turned off then on
Removed adding willpower or brawn modifiers to Wound and Strain calculation, these should be calculated using only base characteristics, even though abilities could increase them, in which users should add ranks manually.
=> Fixed issue with migrating soak from 0.5 to 1.0 schema

README.md, lang/en.json, modules/actors/actor-sheet-ffg.js, modules/combat-ffg.js, templates/dialogs/ffg-initiative.html, templates/parts/actor/ffg-skills.html
(Right-Click on skill and select `Toggle skill as initiative`).
Skills will be prefixed with a `*` on the skill list of the character sheet if they had been added as initiative skills
(Vigilance and Cool will always be initiative skills).
Fixes #404
=> Added ability to add additional skills to initiative dialog.

modules/swffg-main.js
When rolling a nat6, the Dice So Nice Ability die was showing the wrong icon
=> Fix result on the Ability die when rolling a "6" in Dice So Nice

modules/dice/pool.js
DOWNGRADING MORE DICE THAN AVAILABLE
There may be situations where a player needs to downgrade Proficiency dice into Ability dice or Challenge dice into Difficulty dice. If all the potential dice are already in their downgraded form, any further downgrades are ignored
=> downgrading difficulty or ability doesn't remove dice

README.md, template.json
The issue was that when dragging a a weapon from a compendium, it only copies data defined in the template.json, and qualities were not defined there for weapons.
Fixes #648 
NOTE:  This will require a restart of the server running the dev branch!
=> Fix 648 - Fixed issue where qualities were reset on drag/drop.

modules/importer/swa-importer.js
Properly setting the Group Skill flag allows it so that ranks update
correctly as you update the quantity on Minion Actors. Only sets
groupskill to true on minion type adversaries.
=> Set Adversary Group Skill Flag on Import

package-lock.json, scss/components/_dicepool.scss, styles/mandar.css, styles/starwarsffg.css, templates/dice/roll-options-ffg.html
The motivation behind this commit is to improve the readability and reduce the perceived visual complexity of the FFG dice pool dialogue.
Centred the dice to give them more room and balance.
Aligned buttons so that they align with the surrounding elements and blocks.
Added spacing between the different sections.
Reordered buttons to upgrade or downgrade abilities and difficulty so that the ability buttons are on the left and the difficulty buttons are on the right. This matches how the dice are displayed and how the section with the added results is ordered.
The text on these buttons is now left-aligned to improve scanning and readability.
The text explaining how to increase or decrease dice is now emphasised and left-aligned.
Left-aligned the text for the various dice for better scanning …
=> Improve FFG dice pool dialog UI

modules/helpers/dice-helpers.js, modules/helpers/modifiers.js
Unlinked tokens could not roll weapons that were added on their token sheets but not original actor sheets.
#873
=> Allow Unlinked Token Weapon Rolls

modules/importer/oggdude/importers/vehicles.js
Fix #858 - Correct typo of word `weapon` in vehicle.js log message (was `weaon`).
=> Fix #858 - correct typo in vehicle.js log message

modules/items/item-ffg.js
It can get reassigned on next line so changing it to a let to not cause error.
=> Change const to let

modules/importer/import-helpers.js, modules/importer/npc-importer.js, modules/swffg-main.js
This patch introduces an NPC importer tool that is capable of reading and processing exported Adversary XML files from OggDude's GMTools. This is achieved via a new button at the bottom of the Actors tab of FoundryVTT. It has been tested with a number of OggDude's Adversaries as well as my own against the released v1.4 of this system.
With some tweaking, I think this could go some way towards helping move [OggDude Enhancements; Add NPC/Adversary bulk import](https://github.com/StarWarsFoundryVTT/StarWarsFFG/projects/8#card-55699792) along if someone else wanted to create a bulk importer based on this work.
The change to `import-helpers.js` is large, this is mainly because of the addition of static minion and character template objects (instead of having those objects defined literally …
=> Feat: Add OggDude's GMTools NPC Importer Tool

modules/dice/roll-builder.js
Fixes the error when clicking on the symbol instead of the input and allows it to work. #925
=> Fix when clicking on a dice symbol

modules/actors/actor-ffg.js
Any items that aren't weapons, armor, or shipweapons were not getting their adjusted value set so the calculation was incorrect. #937
=> Fix encumbrance calculation

modules/helpers/embeddeditem-helpers.js
Clicking on an item modifier pill gave two errors. One is due to a missing id and the other is not valid permissions. This one fixes the permissions. One of two fixes for #943
=> Item Modifier Viewing Permissions

modules/actors/actor-sheet-ffg.js, modules/dice/roll-builder.js
Added token Data to the getData function of the actor sheet for use in roll builder.
Added token alias and id to speaker information.
This makes it so the name displayed on the roll is the one set on the Token, not the Actors sheet, and allows modules access to the source token of a roll.
=> Speaker Data

modules/dice/roll.js
added results are now added, not overridden when adding them to a roll result.
Fixes Issue #956
=> Bugfix 956 Triumph overrides success

modules/actors/actor-ffg.js
makes sure regular skills flagged as careerskills are also loaded into actor skills
=> Careerskills not loading

templates/chat/force-power-card.html, templates/chat/item-card.html, templates/chat/roll-forcepower-card.html, templates/chat/roll-weapon-card.html
Add data-item-id attribute to outermost HTML element on chat rolls. It allows compatibility with modules that look for the item id in this attribute when an item is rolled (like Maestro). Addresses #970
=> add data-item-id in chat rolls

modules/importer/import-helpers.js
Compendium documents changed the `id` property to a private property. This code switches to using a CompendiumCollection method for getting the document.
Fixes #982
=> fix talent expansion

modules/popout-editor.js
`entities` option  should now be `documents`
=> Fix deprecated option warning in TextEditor.enrichHTML usage.

modules/dice/diceterm.js, modules/dice/dietype/AbilityDie.js, modules/dice/dietype/BoostDie.js, modules/dice/dietype/ChallengeDie.js, modules/dice/dietype/DifficultyDie.js, modules/dice/dietype/ForceDie.js, modules/dice/dietype/ProficiencyDie.js, modules/dice/dietype/SetbackDie.js, modules/swffg-main.js
As DiceTerm#fromMatch was refactored to default to CONFIG.Dice.terms.d for numeric denominators, we have to overwrite it ourselves and go back to the old behaviour.
A bit hacky. I'm sad about it. But it works.
=> Fix numeric dice rolling in Foundry v9.x

modules/items/item-ffg.js, modules/swffg-main.js, system.json
Need to wrap `this.uuid` usage in `this.parent.data` check for older worlds.
Migration of the compendium packs wasn't working as expected. This tries to fix it, but I'm not convinced.
=> Flag bugfixes

modules/actors/actor-sheet-ffg.js
Fix the flag error when creating actors on v9.
The migration code should probably also be updated to make sure to pre-define all levels of data (since it looks like this one got missed), but I'm not familiar with that code.
=> fix(flags): correct flag error when creating actor

modules/dice/roll.js, templates/chat/roll-weapon-card.html
Fixes #1007. Tested on the latest v9 and on `0.8.9`. Note that items with blank qualities included break (not sure if they did already), but it's trivial to fix - just remove the blank quality.
=> fix(qualities): hack to fix item qualities in chat

lang/en.json, modules/dice/roll.js, modules/settings/settings-helpers.js, templates/chat/roll-weapon-card.html
* this mix of data missing happened when I ported my 0.7.10 world. it _should_ be the last combination we have to deal with
* tested and confirmed working on 0.8.9 and v9 (both new and migrated)
#1007
=> fix(qualities): handle yet another case of data missing

modules/actors/actor-sheet-ffg.js, modules/dice/roll-builder.js, modules/dice/roll.js, modules/helpers/actor-helpers.js, modules/helpers/flag-migration-helpers.js, modules/items/itembase-ffg.js, modules/settings/settings-helpers.js, modules/swffg-main.js
fix known migration issues and a few non-migration issues because I forgot this was a migration branch :p
=> V10 world migration

modules/actors/actor-ffg.js, modules/swffg-main.js
* fix embedded item migration on Foundry 10.288 (it was working properly prior to this version but broke again)
* correct calculation of encumbrance
=> V10 migration again

modules/actors/actor-ffg.js
Setting a max of 5 for group skills.
Adding link: #1070
=> Adding in Skill Rank Cap for Minions

templates/dice/roll-options-ffg.html
Fix from @BoltsJ to make the roll window collapse in certain parts to keep the roll button accessible. Issue #958
=> Make parts of roll dialog collapsible

templates/parts/actor/ffg-talents.html
#1110
for some reason, the talentList coming in from minions is in `data.talentList`, while it's `talentList` for PCs/rivals. Rather than spend a bunch of time debugging this, I just added a new block to handle it
=> fix(minions): display talents for minions

modules/actors/actor-ffg-options.js, templates/actors/ffg-character-sheet.html, templates/dialogs/ffg-sheet-options.html
migrate flag setting and lookup (v10 introduced name spaced flags and we didn't fully port all of them for actors)
#1113
=> fix(actors): correct sheet options not displaying

modules/combat-ffg.js
* update accessors to use v10 version
* update to handle async `roll.toMessage`
#1135
=> fix(initiative): fix initiative rolling for Foundry v10

modules/dice/roll.js
I tested using a Discord bot for a bit and enjoyed the shorthand it used for dice so I've made the /roll command able to use that shorthand.
`aapdd` is equivalent to `2da+1dp+2di` (I've put a substitute to allow for `d` or `i` to mean difficulty
This doesn't kick in unless the main parser comes back with a `StringTerm` without a number in it which will fail to evaluate so it shouldn't clash with any existing systems.
=> Added support for 'aapdd' style shorthand dice rolling.

modules/actors/actor-ffg.js, templates/parts/actor/ffg-talents.html
=> Fixed issue with Minion talentList

modules/importer/swa-importer.js
Awoste saw that it was broken. I renamed the function at the last minutes and the IDE didn't rename all the calls. :(
=> Stray 's' from renaming the function to be singular.

modules/helpers/dice-helpers.js
Fix for #1146
Tested by rolling skills with TokenHud
=> Change rollSkillDirect to pass an empty object instead of null for item.

styles/starwarsffg.css
=> style(dice): correct expanded roll card size

modules/importer/import-helpers.js
This PR fixes update of compendium entries when reimporting changes from OggDude over already existing compendia.
After installing StarWarsFFG into a new Foundry v10 install I found out that updating the stock OggDude data with my texts input via the OggDude Data Editor no longer worked in Foundry v10 although the console did not report any errors. In order to fix this I made the following changes:
- Detect and log failed updates
- Log existing compendium entry to make it easier to spot problems when debugging
- Fix the update issue by switching pack caching from `duplicate` to `deepClone` usage
In case you only want some of these changes merged I provided them in separate commits.
My first approach to fixing the issue was to switch back from the non-existing `id` property to the existing …
=> Fix update of compendium entries with OggDude Import in Foundry v10

modules/actors/actor-sheet-ffg.js
The previous implementation looped through all specializations and created a list of selected talents from each specialization, applying the updates to the actor's talent list after each individual specialization. Unfortunately the used `mergeObject()` function does not try to match the talents by name and then replace the appropriate ones, but simply overwrites the array from the beginning. Thus the beginning of the talent list is overwritten up to the maximum selected entries of a single specialization and the remainder of the talent list remains unchanged.
To avoid this, the new implementation constructs a new talent list over all specializations and then sets it as the new talent list once at the end. This approach also fixes another previously unreported bug since handling each …
=> Fix update of talent information on actors

modules/actors/actor-ffg.js
Sorting talents grouped by activation would reverse the alphabetic sorting of the talent names in an activation group to be descending.
This commit changes the sorting to be grouped by activation and alphabetically ascending by talent name in each activation group.
=> Keep alphabetic order of talents in activation groups

modules/swffg-main.js
When processing the journal texts and inserting dice icons the whole HTML of the journal section is replaced, those the element references of the journal's toc point to elements no longer in the document. This commit changes the HTML replacement from using outerHTML to innerHTML as this is somehow necessary for the updated HTMl to be used by Foundry in subsequent hooks.  
This commit also adds another step after the processing of the HTML in which for each toc item the newly created HTML is searched to find the data anchors again. The old references are then replaced by the new ones.
Note that this only fixes a symptom while the root cause is the replacement of huge chunks of the DOM with innerHTML, but the fix for the symptom is easier to achieve right now.
Fixes #1233
=> Fix anchor references of journal toc

modules/groupmanager-ffg.js
Instead of looping through all players checking which actors they own we loop once through all actors checking if they are owned by any active player
Fixes #1230
=> Prevent duplicate actors in group manager

modules/helpers/item-helpers.js, modules/items/item-ffg.js, modules/swffg-main.js
Handle cases where legacy item attachments do not have a `system` property and therefore blow up the system initiation phase before migrations can run to repair the underlying data structure.
=> Fix NPE during legacy item initiation

modules/items/item-sheet-ffg.js
Modifier ranks were being appended as strings. 1+1 would equal 11. Now existing rank and modifier rank are parsed to ints, summed, and made strings again for the item sheet. Remade rank into strings
to try not to break other functionality.
https://github.com/StarWarsFoundryVTT/StarWarsFFG/issues/1219
=> Fix issue 1219: Modifiers append value instead of sum

lang/de.json, lang/en.json, lang/es.json, lang/fr.json, lang/pt-BR.json, modules/config/ffg-modifiers.js, templates/parts/shared/ffg-modifiers.html
Fix item modifier for 'all' type where it was not looking for the type in the right location. 
Fix item modifier for 'vehicle' type by adding new checks.
Add internationalization of 'Vehicle Stats'. Used online translator.
https://github.com/StarWarsFoundryVTT/StarWarsFFG/issues/1223
=> Fix 1223: Missing modifier dropdowns

modules/helpers/embeddeditem-helpers.js, modules/helpers/item-helpers.js, modules/items/item-ffg.js, modules/items/item-sheet-ffg.js, modules/items/itembase-ffg.js, styles/mandar.css, templates/items/ffg-itemattachment-sheet.html, templates/parts/shared/ffg-block.html
Fixes item mods (which have been broken since Foundry `0.8.x`.) You can now add them, remove them, activate them, and edit them. This also removes further legacy `data.data` calls I've somehow missed...
=> Mods on attachments 1191

styles/mandar.css, styles/starwarsffg.css
* enlarges item images for gear and critical injuries
* also fixes a weird Mandar theme bug where images were displayed in the wrong place
#542
=> feat(items): enlarge item images

modules/config/ffg-skillslist.js, modules/swffg-main.js, template.json
* star wars social skills were previously incorrectly tagged as "general", resulting in them not being grouped together in actor sheets
#1318
=> fix(skills): update skill groupings

scss/components/_specializations.scss, scss/components/_talent_blocks.scss, styles/mandar.css, styles/starwarsffg.css
* talents in specializations are now spaced vertically further apart
* this change has been made for all talent-upgrade CSS classes
* changes made for both themes
#1054
=> style(specialization): increase vertical spacing

templates/parts/shared/ffg-block.html
* now properly displays the ranks of a quality from multiple, identical mods on an attachment
#1307
=> fix(attachments): correctly display qualities from attachments

modules/items/item-ffg.js, templates/items/ffg-itemmodifier-sheet.html
* itemmodifier ranks are now displayed to the user
* these ranks can be set to null. if set to null, the quality is shown as unranked
* ranks are still treated as only 1 from each added mod on an attachment
#899
=> fix(mods): permits removing mod rank

lang/en.json, modules/combat-ffg.js, modules/helpers/partial-templates.js, modules/swffg-main.js, scss/components/_combat_tracker.scss, scss/starwarsffg.scss, styles/mandar.css, styles/starwarsffg.css, templates/dialogs/combat-tracker.html
* adds support for toggle-able generic slots
* tokens in a combat can claim slots on a per-round basis
* the GM can un-claim slots
* unused slots are automatically shown
#1323
=> feat(combat): add generic combat slots

modules/combat-ffg.js
* fixes a bug where new combats don't have flags, resulting in a blank tracker
classic, am I right? :p
=> fix(combat): look up claims properly

modules/items/item-ffg.js, modules/swffg-main.js, templates/chat/roll-weapon-card.html
* now embeds item quality data in chat messages instead of linking to it
* this means that previous messages will always properly link to the item at tht time of sending messages, even if items are deleted or users don't have permission to view them
* existing messages will use existing logic
#1336
=> feat(chat): update quality links

modules/helpers/journal.js, modules/swffg-main.js
* text-to-dice renderer now uses the native Foundry rendering for Journals
* secret text blocks can now be displayed/hidden normally
#1299
Note that the code here is essentially just ported from the existing function. It's not really anything new.
=> fix(journals): change dice renderer

scss/components/_skills.scss, styles/starwarsffg.css
* fix skill scrolling in default theme
#1351
=> style(actor): fix scrolling

modules/combat-ffg.js
* you can now claim a slot without selecting a token if you own exactly 1 token on the scene
* this is mainly for players, to reduce their workload
#1373
=> fix(combat): improve slot claiming

modules/combat-ffg.js, templates/dialogs/combat-tracker.html
* now properly handles removing combatants by swapping claims of slots to the ID of the slot, rather than the index of it
#1340
=> fix(combat): correct claimed slot bug

modules/importer/data-importer.js, modules/importer/import-helpers.js, modules/importer/oggdude/importers/species.js, modules/items/item-sheet-ffg.js, modules/swffg-main.js, styles/mandar.css, template.json, templates/items/ffg-species-sheet.html
* allows species to have talents
* when a character gains a species with talents, those talents are added to the character
* when a character loses a species with talents, those talents are removed from the character
* updates the importer to pull in species talents by default
* fixes a bug with career importing wherein specializations would duplicate each time the importer was run
* fixes a bug where attributes were not properly updated on multiple importer runs
#1171
=> feat(species): allow species to have talents

.github/main.yml
* add github action for creating a release artifact
* add github action to post release to Foundry (it is set in dry-run mode until it runs successfully)
=> ci(release): add github actions

CHANGELOG.md, lang/en.json, templates/parts/actor/ffg-skills.html
* update minion skill groups to say "group skill" instead of "career skill"
#1470
=> fix(sheets): minion skills

CHANGELOG.md, modules/combat-ffg.js
* fix for claiming a slot sometimes resulting in two actors showing as having gone
#1465
=> fix(combat): combat-tracker

CHANGELOG.md, modules/items/item-sheet-ffg.js
* fix default Signature ability height so the bottom isn't ever-so-slightly cut off
#1456
=> fix(item): signature ability

CHANGELOG.md, modules/actors/actor-sheet-ffg.js, styles/mandar.css, templates/parts/actor/ffg-skills.html
* "fix" for bug where the contextmenu allowing purchasing ranks in skills does not show up in the bottom few rows
* "fix" in quotes since this adds a new button to purchase
#1454
=> fix(xp): xp spending

CHANGELOG.md, templates/actors/ffg-character-sheet.html, templates/parts/shared/ffg-block.html
* moves all obligation/duty/conflict/morality info to a dedicated tab (leaving the bio tab for the biography only)
* moves the XP available/total fields to the XP log tab
* stops showing edit button on XP log, as it is currently read only
#1473
=> feat(actor): move obligation

.gitignore, CHANGELOG.md, modules/items/item-sheet-ffg.js, styles/mandar.css, templates/items/ffg-specialization-sheet.html
- Modifies the size of the window; scales the talent blocks as the window resizes; updates the appearance of the talent connectors
- Increases the default size of the pop-out editor
This is a small overhaul of the Specialization sheet, intended to improve legibility and add better scaling.
**Updated Sheet:**
**Scaling:**
Question: Is there no sass/scss source for the mandar theme?
=> Modifications to the Specialization Sheet

CHANGELOG.md, modules/helpers/journal.js
Updates the RegExp used when processing tags (`[B]`, etc); allows the processor to properly convert nested tags (e.g., `[B]Average ([di][di]) check[b]`.
Side thought: it may not even be necessary to worry about enclosing many of these tags (from `[B]...[b]` to `<b>...</b>`) -- you could probably just do a straight `[B]` -> `<b>` / `[b]` -> `</b>` and it'll be fine.
=> Improved TextEditor enrichers for nested tag parsing

CHANGELOG.md, modules/dice/roll.js
This PR fixes non FFG dice formula being rejected when more than one term was present.
`+` operators were systematically added between terms of the formula, e.g. `2d6 + 1` became `2d6 + + + 1`
A check has been added to only add `+` between two non operator terms.
Closes #1664
=> fix(dice): + not added before or after operators

CHANGELOG.md, modules/actors/actor-ffg.js
Fix an incorrect test applying token defaults (and resetting other settings) when copying actors.
Closes #1673
=> fix(actor): retain token settings when copying actor

CHANGELOG.md, lang/en.json, lang/fr.json, modules/groupmanager-ffg.js, modules/settings/settings-helpers.js, modules/settings/ui-settings.js
This PR is an example implementation of the option to have GM characters be treated as Player characters in the Group Manager..
The option is located in the Group Manager Settings.
Closes #1680
=> feat(actors): show GM characters in group manager

CHANGELOG.md, modules/ffg-destiny-tracker.js
This PR tentatively fixes the main menu not being toggled with the escape key, except with a token selected.
Hitting the escape key triggers the first of a bunch of ui changes. The ones that interest us here are:
- close at least a window
- unselect a token
- toggle the main menu
The group manager/destiny tracker is always open, so "close a window" was always triggered on it, but its close method doesn't actually close it, as it mus remain visible.  Instead it contains the main menu toggle code.
No window being actually closed means we stop at "unselect a token" if one is selected, or "toggle the main menu" *again* if not.
*Tentatively* because I couldn't find why the main menu toggle code was here, and I'm not sure if I'm not missing something.
Closes #1670
=> fix(ui): main menu toggles normally

CHANGELOG.md, modules/helpers/item-helpers.js, modules/items/item-sheet-ffg.js, modules/items/itembase-ffg.js
This PR fixes a specialization tree not being updated when talents within it are edited.
`item-helpers.js` referenced `formData.data.description` whereas the template stored the description in `system.description`.
The `clickfromparent` list was lost during a call to `Item.update`.
The modification of the hook allows it to be created every time a talent is opened, not just the first one, but it references a Foundry API private property (`_priorState`).
I think we could use the `ItemSheet.close()` method instead to reset the `clickfromparent` list. I have a commit ready if needed [here](https://github.com/obrenckle/StarWarsFFG/tree/move_hook_to_close).
Closes #1643
=> fix(specialization): Updating a talent from a tree updates the tree

CHANGELOG.md, modules/items/item-sheet-ffg.js
This PR fixes mods added on the fly to item attachments having no type defined, and only allowing basic mods instead of weapon/armour/vehicule/all mods.
Changing the item attachment mod type doesn't change the on the fly mods type retroactively, so we could also always set these to "all" instead. If so I'll update the PR.
Closes #1624
=> fix(item): Item attachment mods use parent item mod type

CHANGELOG.md, modules/importer/import-helpers.js
This PR fixes Force Boost mods being imported as Skill Boost mods.
Closes #1687
=> fix(import): Use correct type for Force Boost mods

CHANGELOG.md, modules/items/itembase-ffg.js
This PR fixes an error occurring when checking data.flags.clickfromparent type while data.flags doesn't exists and one incorrect path using data instead of data.system.
Closes #1689
=> fix(item): improves itembase logic

CHANGELOG.md, modules/items/item-ffg.js, modules/items/itembase-ffg.js
This PR fixes a check preventing a parent item uuid from being added to an attachment.
Closes #1612
=> fix(items): Add parent item uuid to qualities

CHANGELOG.md, modules/items/item-ffg.js, templates/items/ffg-specialization-sheet.html
This PR fixes talent cost not being initialized the first time a spec is open.
Closes #1704
=> fix(items): Set talent cost when preparing Tree

CHANGELOG.md, modules/ffg-destiny-tracker.js
This PR remove the hardcoded destiny tracker window size, allowing it to grow and shrink.
This is only a partial fix for #1688, as the UI still has to be reloaded before the window will shrink or grow, but I couldn't find how to trigger a window redraw (which hook to use).
=> fix(ui): remove destiny tracker hardcoded size

CHANGELOG.md, modules/importer/oggdude/importers/item-attachments.js
This PR fixes the type of modifiers assigned to imported armor attachments.
Imported type was "armor" whereas internal type is "armour".
Closes #1697
=> fix(items): assign correct internal mod type to armor attachements

CHANGELOG.md, modules/helpers/actor-helpers.js
This PR fixes zero not being considered a valid value when updating some vehicle stats.
`if (0)` is  false, `Number.isInteger(...)` check if a numeric value was input and accepts 0 as valid.
This closes #1717
=> fix(actor): allow zero as new value

CHANGELOG.md, modules/actors/actor-sheet-ffg.js, modules/helpers/embeddeditem-helpers.js, modules/importer/import-helpers.js, modules/items/item-sheet-ffg.js, modules/swffg-main.js
This PR migrates the deprecated calls to `Document.createDocuments()` for temporary documents to the constructor `Document()` syntax.
Closes #1683
=> fix(import): move from deprecated Document.createDocuments

CHANGELOG.md, lang/en.json, lang/fr.json, modules/dice/pool.js, modules/helpers/dice-helpers.js, modules/settings/settings-helpers.js
This PR should include removed setback dice icons in all roll windows, and actually remove setback dice when rolling the dice.
I've seen your answer on issue [#1719](https://github.com/StarWarsFoundryVTT/StarWarsFFG/issues/1719) and I'm wondering if it applies to my fix. Conditional "remove setback dice" bonus don't seem to be added as modifiers to the talent (at least when using oggdude's importer, e.g. Outdoorsman talent from Pathfinder spec), so any "remove setback dice" modifier present should apply to every roll of that skill.
Closes #1720
=> fix(rolls): use "removed setaback dice" modifiers

CHANGELOG.md, modules/dice/roll.js
In Step 3 of the ffg roll evaluate an array of promises is waited on. In the creation of this array  a value was being returned instead of a promise. I've updated the code to await the promise and its 'then' function
#1731
=> Issue 1731: Standard Rolling Dice Do Not Show Sum

CHANGELOG.md, modules/helpers/dice-helpers.js
I made the logic to get defense die its own function and also made it check against item metadata to see if it has a weapon tag. I then added a call to this new function in the rollItem logic.
#1603
=> Issue 1603 Use Defense when building dice pool does not work on itemRoll

modules/actors/actor-ffg.js
Fix for #1913 
Simple conditional to check if the strain stat is truthy before updating it. This fixes the issue with not being able to modify the willpower of rivals since rivals don't have a strain stat.
=> added conditional for strain before updating

CHANGELOG.md, modules/actors/actor-sheet-ffg.js
Fixes #1909 at the cost of making it not possible to undo an XP adjustment, but the fix for that is just to re-adjust.
=> #1909 removed active effect for xp adjustments

CHANGELOG.md, modules/actors/actor-sheet-ffg.js
* fix bug where Soak was not increased when a point in Brawn was purchased
#1905
=> fix(purchase): soak

CHANGELOG.md, modules/items/item-sheet-ffg.js
* fix talent Ranked property not being transferred when it's drag-and-dropped onto a specialization
#1938
=> fix(talents): drag-and-drop Ranked property

system.json
* additionally marks Foundry v12 as the maximum version, since v13 is known to be incompatible
=> chore(system): prep for 1.909 release

CHANGELOG.md, modules/swffg-main.js
Currently when one of players/GMs adds species to character list (or removes it), callback is called on each client online to add species' talents, so if player creates characters and there is GM online - player's character would receive twice as much talents (and can't delete duplicates, as they are fromSpecies=true). Deleting species deletes only one of each talent, so adding-deleting Droid to character leaaves you with character list with Enduring which can't be removed (possibly it is better to delete each fromSpecies=true items instead). Also each other player tries to do the same modification and gets 'no permission to modify' error or 'item does not exist'.
=> Limit callbacks execution to originating user
